/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.gregbugaj.speedtest;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int btnStart=0x7f050004;
        public static final int connectionspeeed=0x7f050000;
        public static final int networktype=0x7f050003;
        public static final int progress=0x7f050002;
        public static final int speed=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int network_3g=0x7f040002;
        public static final int network_detecting=0x7f040003;
        public static final int network_edge=0x7f040001;
        public static final int update_connectionspeed=0x7f040006;
        public static final int update_downloaded=0x7f040005;
        public static final int update_downloaded_complete=0x7f040007;
        public static final int update_speed=0x7f040004;
    }
}
